
using PyPlot
using DataFrames
using CSV
using KernelDensity
using Distributions

include(pwd()*"/src/g and k dist/set_up.jl")

chain = Matrix(CSV.read("data/gandk/exact_inference_post.csv"; allowmissing=:auto))
posterior_summary_stats = Matrix(CSV.read("data/gandk/abcrs_post.csv"; allowmissing=:auto))
posterior_simple_DNN_small = Matrix(CSV.read("data/gandk/abcrs_post_simple_DNN_small.csv"; allowmissing=:auto))
posterior_simple_DNN_large = Matrix(CSV.read("data/gandk/abcrs_post_simple_DNN_small.csv"; allowmissing=:auto))
posterior_timeseries_data = Matrix(CSV.read("data/gandk/abcrs_post_dnn_timseries_data.csv"; allowmissing=:auto))
posterior_deepsets = Matrix(CSV.read("data/gandk/abcrs_post_deepsets.csv"; allowmissing=:auto))


# calc grid for prior dist
x_grid = -0.5:0.01:10.5

# calc prior dist
priordensity1 = pdf.(Gamma(2,1), x_grid)
priordensity2 = pdf.(Gamma(2,1), x_grid)
priordensity3 = pdf.(Gamma(2,0.5), x_grid)
priordensity4 = pdf.(Gamma(2,1), x_grid)

# exact inference

h1_exact = kde(chain[:,1])
h2_exact = kde(chain[:,2])
h3_exact = kde(chain[:,3])
h4_exact = kde(chain[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")



# ABC

h1 = kde(posterior_summary_stats[:,1])
h2 = kde(posterior_summary_stats[:,2])
h3 = kde(posterior_summary_stats[:,3])
h4 = kde(posterior_summary_stats[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b--")
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b--")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b--")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b--")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")


# simple DNN small
h1 = kde(posterior_simple_DNN_small[:,1])
h2 = kde(posterior_simple_DNN_small[:,2])
h3 = kde(posterior_simple_DNN_small[:,3])
h4 = kde(posterior_simple_DNN_small[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b--")
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b--")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b--")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b--")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")


# simple DNN large
h1 = kde(posterior_simple_DNN_large[:,1])
h2 = kde(posterior_simple_DNN_large[:,2])
h3 = kde(posterior_simple_DNN_large[:,3])
h4 = kde(posterior_simple_DNN_large[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b--")
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b--")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b--")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b--")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")


# simple DNN timeseries data
h1 = kde(posterior_timeseries_data[:,1])
h2 = kde(posterior_timeseries_data[:,2])
h3 = kde(posterior_timeseries_data[:,3])
h4 = kde(posterior_timeseries_data[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b--")
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b--")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b--")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b--")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")


#  DNN deepsets
h1 = kde(posterior_deepsets[:,1])
h2 = kde(posterior_deepsets[:,2])
h3 = kde(posterior_deepsets[:,3])
h4 = kde(posterior_deepsets[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b--")
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b--")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b--")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b--")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")
