
using PyPlot
using DataFrames
using CSV
using KernelDensity
using Distributions

include(pwd()*"/src/multivar alpha stable dist/set_up.jl")

chain = Matrix(CSV.read("data/gandk/exact_inference_post.csv"; allowmissing=:auto))
posterior_summary_stats = Matrix(CSV.read("data/multivar alpha stable/abcrs_post.csv"; allowmissing=:auto))
posterior_simple_DNN_small = Matrix(CSV.read("data/multivar alpha stable/abcrs_post_simple_DNN_small_1.csv"; allowmissing=:auto))
posterior_timeseries_data = Matrix(CSV.read("data/multivar alpha stable/abcrs_post_dnn_timseries_data_1.csv"; allowmissing=:auto))
posterior_deepsets = Matrix(CSV.read("data/multivar alpha stable/abcrs_post_deepsets_1.csv"; allowmissing=:auto))

# calc grid for prior dist
x_grid1 = 1:0.01:2.1
x_grid2 = -3:0.01:3
x_grid3 = -0.1:0.01:2*pi+0.1
x_grid4 = -0.1:0.01:1+0.1

# calc prior dist
priordensity1 = pdf.(Uniform(1.1,2), x_grid1)
priordensity2 = pdf.(Normal(0,1), x_grid2)
priordensity3 = pdf.(Uniform(0,2*pi), x_grid3)
priordensity4 = pdf.(Beta(2,2), x_grid4)

# exact inference

h1_exact = kde(chain[:,1])
h2_exact = kde(chain[:,2])
h3_exact = kde(chain[:,3])
h4_exact = kde(chain[:,4])

PyPlot.figure()
PyPlot.subplot(221)
PyPlot.plot(h1_exact.x,h1_exact.density, "b")
PyPlot.plot(x_grid,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1_exact.density)), "k")
PyPlot.ylabel(L"Density")
PyPlot.xlabel(L"$A$")
PyPlot.subplot(222)
PyPlot.plot(h2_exact.x,h2_exact.density, "b")
PyPlot.plot(x_grid,priordensity2, "g")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2_exact.density)), "k")
PyPlot.xlabel(L"$B$")
PyPlot.subplot(223)
PyPlot.plot(h3_exact.x,h3_exact.density, "b")
PyPlot.plot(x_grid,priordensity3, "g")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3_exact.density)), "k")
PyPlot.xlabel(L"$g$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(224)
PyPlot.plot(h4_exact.x,h4_exact.density, "b")
PyPlot.plot(x_grid,priordensity4, "g")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4_exact.density)), "k")
PyPlot.xlabel(L"$k$")



# ABC
h1 = kde(posterior_summary_stats[:,1])
h2 = kde(posterior_summary_stats[:,2])
h3 = kde(posterior_summary_stats[:,3])
h4 = kde(posterior_summary_stats[:,4])
h5 = kde(posterior_summary_stats[:,5])
h6 = kde(posterior_summary_stats[:,6])

PyPlot.figure()
PyPlot.subplot(321)
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid1,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1.density)), "k")
PyPlot.xlabel(L"$α$")
PyPlot.subplot(322)
PyPlot.plot(x_grid2,priordensity2, "g")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2.density)), "k")
PyPlot.xlabel(L"$μ_0$")
PyPlot.subplot(323)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3.density)), "k")
PyPlot.xlabel(L"$ϕ_1$")
PyPlot.subplot(324)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4.density)), "k")
PyPlot.xlabel(L"$ϕ_2$")
PyPlot.subplot(325)
PyPlot.plot(h5.x,h5.density, "b")
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot((θ_true[5], θ_true[5]), (0, maximum(h5.density)), "k")
PyPlot.xlabel(L"$w_1$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(326)
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot(h6.x,h6.density, "b")
PyPlot.plot((θ_true[6], θ_true[6]), (0, maximum(h6.density)), "k")
PyPlot.xlabel(L"$w_2$")


# simple DNN small
h1 = kde(posterior_simple_DNN_small[:,1])
h2 = kde(posterior_simple_DNN_small[:,2])
h3 = kde(posterior_simple_DNN_small[:,3])
h4 = kde(posterior_simple_DNN_small[:,4])
h5 = kde(posterior_simple_DNN_small[:,5])
h6 = kde(posterior_simple_DNN_small[:,6])

PyPlot.figure()
PyPlot.subplot(321)
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid1,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1.density)), "k")
PyPlot.xlabel(L"$α$")
PyPlot.subplot(322)
PyPlot.plot(x_grid2,priordensity2, "g")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2.density)), "k")
PyPlot.xlabel(L"$μ_0$")
PyPlot.subplot(323)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3.density)), "k")
PyPlot.xlabel(L"$ϕ_1$")
PyPlot.subplot(324)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4.density)), "k")
PyPlot.xlabel(L"$ϕ_2$")
PyPlot.subplot(325)
PyPlot.plot(h5.x,h5.density, "b")
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot((θ_true[5], θ_true[5]), (0, maximum(h5.density)), "k")
PyPlot.xlabel(L"$w_1$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(326)
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot(h6.x,h6.density, "b")
PyPlot.plot((θ_true[6], θ_true[6]), (0, maximum(h6.density)), "k")
PyPlot.xlabel(L"$w_2$")


# simple DNN timeseries data
h1 = kde(posterior_timeseries_data[:,1])
h2 = kde(posterior_timeseries_data[:,2])
h3 = kde(posterior_timeseries_data[:,3])
h4 = kde(posterior_timeseries_data[:,4])
h5 = kde(posterior_timeseries_data[:,5])
h6 = kde(posterior_timeseries_data[:,6])

PyPlot.figure()
PyPlot.subplot(321)
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid1,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1.density)), "k")
PyPlot.xlabel(L"$α$")
PyPlot.subplot(322)
PyPlot.plot(x_grid2,priordensity2, "g")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2.density)), "k")
PyPlot.xlabel(L"$μ_0$")
PyPlot.subplot(323)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3.density)), "k")
PyPlot.xlabel(L"$ϕ_1$")
PyPlot.subplot(324)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4.density)), "k")
PyPlot.xlabel(L"$ϕ_2$")
PyPlot.subplot(325)
PyPlot.plot(h5.x,h5.density, "b")
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot((θ_true[5], θ_true[5]), (0, maximum(h5.density)), "k")
PyPlot.xlabel(L"$w_1$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(326)
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot(h6.x,h6.density, "b")
PyPlot.plot((θ_true[6], θ_true[6]), (0, maximum(h6.density)), "k")
PyPlot.xlabel(L"$w_2$")


#  DNN deepsets
h1 = kde(posterior_deepsets[:,1])
h2 = kde(posterior_deepsets[:,2])
h3 = kde(posterior_deepsets[:,3])
h4 = kde(posterior_deepsets[:,4])
h5 = kde(posterior_deepsets[:,5])
h6 = kde(posterior_deepsets[:,6])

PyPlot.figure()
PyPlot.subplot(321)
PyPlot.plot(h1.x,h1.density, "b")
PyPlot.plot(x_grid1,priordensity1, "g")
PyPlot.plot((θ_true[1], θ_true[1]), (0, maximum(h1.density)), "k")
PyPlot.xlabel(L"$α$")
PyPlot.subplot(322)
PyPlot.plot(x_grid2,priordensity2, "g")
PyPlot.plot(h2.x,h2.density, "b")
PyPlot.plot((θ_true[2], θ_true[2]), (0, maximum(h2.density)), "k")
PyPlot.xlabel(L"$μ_0$")
PyPlot.subplot(323)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h3.x,h3.density, "b")
PyPlot.plot((θ_true[3], θ_true[3]), (0, maximum(h3.density)), "k")
PyPlot.xlabel(L"$ϕ_1$")
PyPlot.subplot(324)
PyPlot.plot(x_grid3,priordensity3, "g")
PyPlot.plot(h4.x,h4.density, "b")
PyPlot.plot((θ_true[4], θ_true[4]), (0, maximum(h4.density)), "k")
PyPlot.xlabel(L"$ϕ_2$")
PyPlot.subplot(325)
PyPlot.plot(h5.x,h5.density, "b")
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot((θ_true[5], θ_true[5]), (0, maximum(h5.density)), "k")
PyPlot.xlabel(L"$w_1$")
PyPlot.ylabel(L"Density")
PyPlot.subplot(326)
PyPlot.plot(x_grid4,priordensity4, "g")
PyPlot.plot(h6.x,h6.density, "b")
PyPlot.plot((θ_true[6], θ_true[6]), (0, maximum(h6.density)), "k")
PyPlot.xlabel(L"$w_2$")
